sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.prod -t docker-react .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-162532840770"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY "
